var myName = "John";
var age = 25;
var isStudent = true;
var address = null;
console.log("Name: ".concat(myName));
console.log("Age: ".concat(age));
console.log("Is Student: ".concat(isStudent));
console.log("Address: ".concat(address));
age = 42;
isStudent = false;
address = "main street";
console.log("Updated Age: ".concat(age));
console.log("Updated Is Student: ".concat(isStudent));
console.log("Updated Address: ".concat(address));
